name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    # fire only when someone actually @‑mentions Claude
    if: |
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' &&
       contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' &&
       contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' &&
       (contains(github.event.issue.body, '@claude') ||
        contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest

    # rights the auto‑generated GITHUB_TOKEN will receive
    permissions:
      contents: write        # push commits
      pull-requests: write   # update / open PRs
      issues: write          # post comments
      id-token: write        # OIDC (if needed by Claude)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # let Claude run git diff / log

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v0.0.7   # pin to patched release
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token:     ${{ secrets.GITHUB_TOKEN }}

          # allow Claude to run the commands it needs
          allowed_tools: |
            Bash(node:*),     # node --version, node scripts
            Bash(npm:*),      # npm ci, npm run lint, npm run build …
            Bash(git:*),      # git status / diff / add / commit …
            Bash(*),          # any other Bash one‑offs (remove later if you want stricter lockdown)
            View,
            GlobTool,
            GrepTool,
            BatchTool
